version: '3'
services:
  message-service:
    image: tomcat:9.0-jre10
    ports:
      - "8888:8080"
    volumes:
      - ./target/restfulmavenapp.war:/usr/local/tomcat/webapps/ROOT.war
      - ./target/restfulmavenapp:/usr/local/tomcat/webapps/ROOT

