# Payara support. Run docker run --rm -it -v $(pwd):/project -w /project maven mvn package && docker-compose -f payara-docker-compose.yml up
version: '3'
services:
  message-service:
    image: payara/server-full:5.183
    ports:
      - 8082:8080
      - 4848:4848
    volumes:
      - ./target/restfulmavenapp.war:/payara/deployments/restfulmavenapp.war
      - ./target:/opt/payara/deployments
        

